language: ruby
service:
 - docker
email: false
before_script:
- docker pull golang:1.13
- docker pull golang:1.14
script:
- docker run --rm -it -e GO111MODULE=on -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:1.13 $(pwd)/init-docker-go.sh
- docker run --rm -it -e GO111MODULE=on -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:1.14 $(pwd)/init-docker-go.sh
