language: go
go:
- 1.12.x
- 1.13.x
- 1.14.x
- master
sudo: false
email: false
install:
 - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
 - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
before_script:
 - go vet ./...
script:
- env GO111MODULE=on go test -v ./...
- env GO111MODULE=on go build -v ./...
