language: go

env: GO111MODULE=on GOFLAGS='-mod vendor'

branches:
  only:
  - master

go:
- 1.14

git:
  depth: 1

install: true

email: false

before_script:
- curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.23.1
script:
- golangci-lint run       # run a bunch of code checkers/linters in parallel
- go test -v -race ./...  # Run all the tests with the race detector enabled
- go build -v -race ./...  # Run all the tests with the race detector enabled

