language: go
go:
- master
sudo: false
email: false
install:
 - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
 - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
 - export GO111MODULE=off
before_script:
 - go vet ./...
script:
- go test -v ./...
- go build -v ./...
