language: ruby
service:
 - docker
email: false
before_script:
- docker pull golang:1.13
- docker pull golang:1.14
script:
- docker run --rm -it -e GO111MODULE=off -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:1.13 go mod init && go mod tidy && go build -v ./...
- docker run --rm -it -e GO111MODULE=off -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:1.14 go mod init && go mod tidy && go build -v ./...
