language: go
go:
 - 1.12.x
 - 1.13.x
 - 1.14.x
- master
sudo: false
email: false
before_script:
- go vet ./...
install: true
script:
 # Add Godeps dependencies to GOPATH and PATH
- export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
- export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
- env GO111MODULE=on go test -v ./...
- env GO111MODULE=on go build -v ./...
