deployname: My first deployment
useHosts:
- hosts-dev
useVars:
- vars.yaml
configDir: env
chartsDir: charts
modulesDir: .
systemDir:
configLang: YAML
env: dev
verbosity: INFO
parallel: true
maxThreads: 10
singleSession: true